### ISSUE TITLE
MoveIt setup assistant not working

### ISSUE THREAD

**Issue by yureklimert** [RoboStack/ros-noetic#132]
<img width="568" alt="setup_assistant_issue" src="https://user-images.githubusercontent.com/71176035/120148592-265f7000-c1f1-11eb-9177-8b82f01ff074.png">

After I downloaded moveIt into my workspace when I tried to open moveit_setup_assistant on my terminal with roslaunch moveit_setup_assistant setup_assistant.launch, It is sticking like image above and in the dock this image appears 

<img width="246" alt="Screen Shot 2021-05-31 at 09 25 19" src="https://user-images.githubusercontent.com/71176035/120149353-45aacd00-c1f2-11eb-86e3-3c304a652424.png">
 
After that nothing happens and this is the screen when It is shuted down with ctrl + C

<img width="568" alt="Screen Shot 2021-05-31 at 09 27 41" src="https://user-images.githubusercontent.com/71176035/120149556-902c4980-c1f2-11eb-8b47-bd15301fc4ea.png">

**Comment by Tobias-Fischer** [comment]
Hiya @yureklimert,
Many thanks for reporting this bug. I've just uploaded a new version - please `mamba upgrade ros-noetic-moveit-setup-assistant` and it should work. Please re-open the issue if not.

@traversaro @wolfv - it's the same issue as with rviz - it needs building with macos version 10.9 instead of 10.14. We might need to dig again and/or only use 10.14 in the packages that actually need it. I'll update #69

**Comment by yureklimert** [comment]
Thank you for helping. I am using macOS 11.4 and everything works with no problem.

**Comment by yureklimert** [comment]
Thank you for helping problem solved. Also I am using macOS 11.4 and everything works perfectly fine.

**Comment by Tobias-Fischer** [comment]
Great, thanks for letting us know!
